version: '3.7'
services:
    ordering-service:
        build: orderingService/
        env_file: ./.env
        restart: always
        volumes: 
            - ./orderingService:/orderingService
        ports: 
            - "${ORDERING_C_PORT}:${ORDERING_N_PORT}"
        depends_on: 
            - mongo-db
        networks: 
            net:
    users-service:
        build: usersService/
        env_file: ./.env
        restart: always
        volumes: 
            - ./usersService:/usersService 
            - ./externalVolumes/userImages:/usersService/userImages 
        ports: 
            - "${USERS_C_PORT}:${USERS_N_PORT}"
        depends_on: 
            - mongo-db
        networks: 
            net: 
    products-service:
        build: productsService/ 
        env_file: ./.env
        restart: always
        volumes: 
            - ./externalVolumes/images:/productsService/productsImages 
            - ./productsService:/productsService
        ports: 
            - "${PRODCUTS_C_PORT}:${PRODCUTS_N_PORT}"
        depends_on: 
            - mongo-db
        networks:
            net:
    mongo-db: 
        image: mongo
        restart: always
        ports:
            - "27017:27017"
        volumes:
            - mongo:/var/lib/mongo
            - ./externalVolumes/db:/data/db
        networks:
            net:
volumes:
  mongo:
networks: 
    net:
        driver: bridge
